[files]
extend-exclude = [
    "/descriptions-sources/",
    "/assets/modules/",
]

[type.md]
extend-glob = ["*.md"]
check-filename = false

[type.md.extend-identifiers]
# Microsoft spelling.
SystemPrioritySeperation = "SystemPrioritySeperation"
